### ISSUE TITLE
Populating alias fields

### ISSUE THREAD

**Issue by OkomelaIT** [ActiveIS/ActiveIS.UmbracoForms.Loqate#1]
Hello,

I am currently unable to populate the link Umbraco Forms field with the selected address details.

The search is working but once the final address is selected it does not populate the address fields.

![image](https://user-images.githubusercontent.com/2866916/86999965-cceeec80-c1ab-11ea-8dd3-b500436e977e.png)

They have been linked in the Umbraco BackOffice:

![image](https://user-images.githubusercontent.com/2866916/87000078-1c351d00-c1ac-11ea-8770-277fd9c4f609.png)

Any pointers will be greatly appreciated.

Thanks

**Comment by AaronSadlerUK** [comment]
Have you added the following to the class for each FieldType:

` @Model.Alias`

So for example the text field class would look like this:

`class="@Model.Alias"`

This would need to be added in addition to any existing classes

I will update the documentation for this, and I will look to change how this works in a future version, so that it uses the field ID rather than a class.

**Comment by OkomelaIT** [comment]
Hello Aaron,

Thanks for that, it worked perfectly.
